.gitmessage, src/main/java/br/com/mercadolivre/defafioquality/database/FileManager.java, src/main/java/br/com/mercadolivre/defafioquality/exceptions/DatabaseManagementException.java, src/main/java/br/com/mercadolivre/defafioquality/exceptions/DatabaseReadException.java, src/main/java/br/com/mercadolivre/defafioquality/exceptions/DatabaseWriteException.java, src/main/java/br/com/mercadolivre/defafioquality/exceptions/DbEntryAlreadyExists.java, src/main/java/br/com/mercadolivre/defafioquality/models/Neighborhood.java, src/main/java/br/com/mercadolivre/defafioquality/models/Property.java, src/main/java/br/com/mercadolivre/defafioquality/models/Room.java, src/main/java/br/com/mercadolivre/defafioquality/repository/ApplicationRepository.java, src/main/java/br/com/mercadolivre/defafioquality/services/PropertyService.java, src/main/resources/application.properties
=> Initial project structure with FileManager, Repository interface, Blank PropertyService and Models

src/main/java/br/com/mercadolivre/defafioquality/models/Neighborhood.java
=> hotfix: add Lombok Data annotation on Neighborhood model

src/main/java/br/com/mercadolivre/defafioquality/dto/NeighborhoodDTO.java, src/main/java/br/com/mercadolivre/defafioquality/dto/PropertyDTO.java, src/main/java/br/com/mercadolivre/defafioquality/dto/RoomDTO.java
add new anotations validations for dto's 
closed #6
=> feat: add anotations of validation for dto's

src/main/java/br/com/mercadolivre/defafioquality/services/PropertyService.java
add method calcPropertyPrice as a void on PropertyService
-
start:#17
=> feat: add method calcPropertyPrice as a void

src/main/java/br/com/mercadolivre/defafioquality/exceptions/NullIdException.java, src/main/java/br/com/mercadolivre/defafioquality/exceptions/PropertyNotFoundException.java, src/main/java/br/com/mercadolivre/defafioquality/services/PropertyService.java, src/test/java/br/com/mercadolivre/defafioquality/service/PropertyServiceTests.java
Create assertations false tests to check PropertyService method that calculates requested property total price
close #18
=> Creating tests for PropertyService calc property price

src/main/java/br/com/mercadolivre/defafioquality/services/PropertyService.java, src/test/java/br/com/mercadolivre/defafioquality/service/PropertyServiceTests.java
Implements the logic to calc property value
continue #17
=> feat: implementing logic to calculate property value

src/main/java/br/com/mercadolivre/desafioquality/services/PropertyService.java, src/main/java/br/com/mercadolivre/desafioquality/services/RoomService.java, src/test/java/br/com/mercadolivre/desafioquality/service/PropertyServiceTests.java, src/test/java/br/com/mercadolivre/desafioquality/service/RoomServiceTests.java, src/test/java/br/com/mercadolivre/desafioquality/utils/PropertyUtils.java
=> Feat: Room tests with null values and property total area price method and function

src/main/java/br/com/mercadolivre/desafioquality/services/RoomService.java, src/test/java/br/com/mercadolivre/desafioquality/service/RoomServiceTests.java
=> feat: add some validations and unit test on calculate area method

src/main/java/br/com/mercadolivre/desafioquality/controller/PropertyController.java, src/main/java/br/com/mercadolivre/desafioquality/dto/mapper/PropertyMapper.java, src/main/java/br/com/mercadolivre/desafioquality/dto/response/PropertyResponseDTO.java, src/main/java/br/com/mercadolivre/desafioquality/services/PropertyService.java, src/test/java/br/com/mercadolivre/desafioquality/service/PropertyServiceTests.java
Create a new endpoint for list all properties
start:#32
=> feat: create endpoint for list of properties

src/main/java/br/com/mercadolivre/desafioquality/database/default/neighborhood_default.json, src/main/java/br/com/mercadolivre/desafioquality/database/default/property_default.json, src/main/java/br/com/mercadolivre/desafioquality/services/PropertyService.java
=> add neighborhood validation on property service and fill database (json)

src/main/java/br/com/mercadolivre/desafioquality/controller/PropertyController.java, src/main/java/br/com/mercadolivre/desafioquality/dto/request/CreatePropertyDTO.java, src/main/java/br/com/mercadolivre/desafioquality/dto/request/CreateRoomsDTO.java, src/main/java/br/com/mercadolivre/desafioquality/models/Property.java, src/main/java/br/com/mercadolivre/desafioquality/services/PropertyService.java, src/test/java/br/com/mercadolivre/desafioquality/service/PropertyServiceTests.java
To do it and doesn't have duplicated code, I had to do a minor refactor on PropertyService and Models.
Tests, will be ready on a future PR.
=> refact: property creation endpoints

src/main/java/br/com/mercadolivre/desafioquality/services/RoomService.java
- feat: find the biggest room by property.
close: #28
=> feat: find the biggest room by property

src/main/java/br/com/mercadolivre/desafioquality/controller/NeighborhoodController.java, src/main/java/br/com/mercadolivre/desafioquality/repository/NeighborhoodRepository.java, src/main/java/br/com/mercadolivre/desafioquality/services/NeighborhoodService.java, src/test/java/br/com/mercadolivre/desafioquality/integration/NeighborhoodIntegrationTest.java, src/test/java/br/com/mercadolivre/desafioquality/service/NeighborhoodServiceTests.java, src/test/java/br/com/mercadolivre/desafioquality/utils/DatabaseUtils.java
=> Feat add find and delete operations

src/main/java/br/com/mercadolivre/desafioquality/services/RoomService.java, src/test/java/br/com/mercadolivre/desafioquality/service/RoomServiceTests.java
- test if biggest room is correct
close #54
=> feat: test if biggest room is correct

src/test/java/br/com/mercadolivre/desafioquality/test_utils/PropertyUtils.java, src/test/java/br/com/mercadolivre/desafioquality/unity/service/PropertyServiceTests.java
Refactoring the unity's tests of property service module.
Coverage status :  Class(100%) | Method (100%) | Line(97%)
-
Closed: #09
Closed : #16 
Closed : #32
=> feat: refactoring the tests of Property

src/main/java/br/com/mercadolivre/desafioquality/controller/advice/ValidationExceptionHandler.java, src/main/java/br/com/mercadolivre/desafioquality/services/NeighborhoodService.java
* add handler to deal with exception thrown by validations. 
* compare lowercase names of neighborhods, to avoid duplication.
close #64 
connects #42
=> improvement: add handler to validations

src/test/java/br/com/mercadolivre/desafioquality/integration/RoomIntegrationTest.java
- test get biggest room
close #68
=> feat: test get biggest room

src/main/java/br/com/mercadolivre/desafioquality/controller/PropertyController.java, src/main/java/br/com/mercadolivre/desafioquality/services/PropertyService.java
=> refact: improving response on add new property

src/main/java/br/com/mercadolivre/desafioquality/dto/NeighborhoodDTO.java, src/test/java/br/com/mercadolivre/desafioquality/integration/NeighborhoodIntegrationTest.java, src/test/java/br/com/mercadolivre/desafioquality/test_utils/NeighborhoodUtils.java, src/test/java/br/com/mercadolivre/desafioquality/test_utils/TestUtils.java
- add tests to cover invalid neighborhood attributes
- create method to run test expecting bad request as status code
connects #42
=> improvement: add test cases for NeighborhoodController

src/main/java/br/com/mercadolivre/desafioquality/database/FileManager.java, src/test/java/br/com/mercadolivre/desafioquality/unity/database/FileManagerTests.java
=> Feat add FileManager unit tests

README.md
tinha adicionado o link com as diferenças da pr.
=> acerta link da collection na descrição

src/main/java/br/com/mercadolivre/desafioquality/controller/PropertyController.java, src/main/java/br/com/mercadolivre/desafioquality/dto/request/UpdatePropertyDTO.java, src/main/java/br/com/mercadolivre/desafioquality/repository/ApplicationRepository.java, src/main/java/br/com/mercadolivre/desafioquality/repository/NeighborhoodRepository.java, src/main/java/br/com/mercadolivre/desafioquality/repository/PropertyRepository.java, src/main/java/br/com/mercadolivre/desafioquality/services/NeighborhoodService.java, src/main/java/br/com/mercadolivre/desafioquality/services/PropertyService.java, src/test/java/br/com/mercadolivre/desafioquality/integration/PropertyControllerTests.java, src/test/java/br/com/mercadolivre/desafioquality/unity/service/NeighborhoodServiceTests.java
=> feat: add delete and update routes to property entity
